#ASK_VIDEO_OR_PLAYLIST_STATE = "askvideoorplayliststate"
ASK_FORMAT_STATE = "askformatstate"
ASK_QUALITY_STATE = "askqualitystate"
PUT_URL_STATE = "putlinkstate"
RETURN_FILE_STATE = "returnfilestate"
LOGIN_STATE = "loginstate"